// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuyfmO1cdQ2CKISsi6doVvXNvD6ddj7U',
    appId: '1:280986833025:android:1cf3f9f1675243a5437d80',
    messagingSenderId: '280986833025',
    projectId: 'fire-bank-app',
    storageBucket: 'fire-bank-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuMzv4kpPDyqZvWjst-g3YghmG3Gz7idU',
    appId: '1:280986833025:web:405c059100c4f6ca437d80',
    messagingSenderId: '280986833025',
    projectId: 'fire-bank-app',
    authDomain: 'fire-bank-app.firebaseapp.com',
    storageBucket: 'fire-bank-app.appspot.com',
    measurementId: 'G-015F02Q7X6',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMzv4kpPDyqZvWjst-g3YghmG3Gz7idU',
    appId: '1:280986833025:web:405c059100c4f6ca437d80',
    messagingSenderId: '280986833025',
    projectId: 'fire-bank-app',
    authDomain: 'fire-bank-app.firebaseapp.com',
    storageBucket: 'fire-bank-app.appspot.com',
    measurementId: 'G-015F02Q7X6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAJCuVAvbPXKtSsDgd6nTyaJfbeMRvaI',
    appId: '1:280986833025:ios:4763fd1bb47d8f64437d80',
    messagingSenderId: '280986833025',
    projectId: 'fire-bank-app',
    storageBucket: 'fire-bank-app.appspot.com',
    iosBundleId: 'com.example.bankapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAJCuVAvbPXKtSsDgd6nTyaJfbeMRvaI',
    appId: '1:280986833025:ios:4763fd1bb47d8f64437d80',
    messagingSenderId: '280986833025',
    projectId: 'fire-bank-app',
    storageBucket: 'fire-bank-app.appspot.com',
    iosBundleId: 'com.example.bankapp',
  );

}